Added code for face detection in images.
Aayush-hub/Basic-Python-Projects pull request #16
Opened 2020-10-05 13:48 UTC by GSNCodes

I have also added the requirements file along with a sample input - output pair.

2020-10-05 13:48 UTC, GSNCodes commented
@Aayush-hub Please do add the hactoberfest label to this PR. 
I hope you are happy with my contribution 😄

2020-10-06 04:31 UTC, Aayush-hub requested changes
Please add comments.

2020-10-06 05:45 UTC, GSNCodes commented
@Aayush-hub 
I've added the comments detailing every step as requested 👍

2020-10-06 12:53 UTC, Aayush-hub approved these changes

2020-10-06 12:53 UTC, merged